export const reducerCases = {
    SET_USER: "SET_USER",
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    TOGGLE_SIGNUP_MODAL: "TOGGLE_SIGNUP_MODAL",
    CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
    SET_SELLER: "SET_SELLER",
    SWITCH_MODE: "SWITCH_MODE",
    SET_LISTING_DATA: "SET_LISTING_DATA",
    HAS_USER_ORDERED_LISTING: "HAS_USER_ORDERED_LISTING",
    ADD_REVIEW: "ADD_REVIEW",
};